### ISSUE TITLE
Neoformat/Prettier block not being triggered

### ISSUE THREAD

**Issue by jbranchaud** [hashrocket/vim-hashrocket#13]
Started in on a React project in a dev environment using dotmatrix with vim-hashrocket and the block for Neoformat/Prettier is not being triggered.

https://github.com/hashrocket/vim-hashrocket/blob/master/plugin/hashrocket.vim#L229-L241

Running the conditions of the `if` statement on there own evaluate to the true, but the code in the plugin is not coming through. Need to investigate more.

**Comment by dillonhafer** [comment]
Thanks! This should be resolved now ❤️
